version: '3.10'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_vk_to_tg
    restart: always
    secrets:
      - token_vk
      - token_tg

secrets:
   token_vk:
     file: token_vk
   token_tg:
     file: token_tg
